---
- name: "Install dependencies, Setup PHP"
  yum: pkg={{ item }} state=present
  with_items:
    - php56
    - php56-xml
    - php56-xmlrpc
    - php56-soap
    - php56-gd
    - php56-mysqlnd
    - php56-bcmath
    - php56-mbstring

- name: "Set php timezone"
  lineinfile: >- 
    dest='/etc/php.ini'
    regexp="^date.timezone ="
    insertafter="^;date.timezone ="
    line="date.timezone = {{ dateTimezone }}"

- name: "Set php post_max_size"
  lineinfile: >-
    dest='/etc/php.ini'
    regexp="^post_max_size >"
    insertafter="^;post_max_size >"
    line="post_max_size = {{ post_max_size }}"

- name: "Set php max_execution_time"
  lineinfile: >-
    dest='/etc/php.ini'
    regexp="^max_execution_time ="
    insertafter="^;max_execution_time ="
    line="max_execution_time = {{ max_execution_time }}"

- name: "Set php max_input_time"
  lineinfile: >-
    dest='/etc/php.ini'
    regexp="^max_input_time ="
    insertafter="^;max_input_time ="
    line="max_execution_time = {{ max_input_time }}"

- name: "Set php always_populate_raw_post_data"
  lineinfile: >-
    dest='/etc/php.ini'
    regexp="^always_populate_raw_post_data ="
    insertafter="^;always_populate_raw_post_data ="
    line="always_populate_raw_post_data = {{ always_populate_raw_post_data }}"
