---
- name: "Install dependencies | Setup PHP"
  yum: 
    pkg: "{{ item }}" 
    state: present
  with_items:
    - php56
    - php56-xml
    - php56-xmlrpc
    - php56-soap
    - php56-gd
    - php56-mysqlnd
    - php56-bcmath
    - php56-mbstring
  notify:
    - restart httpd

- name: "Set PHP timezone"
  lineinfile: 
     dest: '/etc/php.ini'
     regexp: '^date.timezone ='
     insertafter: '^;date.timezone ='
     line: "date.timezone = {{ php_date_timezone }}"

- name: "Set PHP post_max_size"
  lineinfile:
     state: present
     dest: '/etc/php.ini'
     regexp: '^(#)?post_max_size = \d'
     line: "post_max_size = {{ php_post_max_size }}"

- name: "Set PHP max_execution_time"
  lineinfile:
     state: present
     dest: '/etc/php.ini'
     regexp: '^(#)?max_execution_time = \d'
     line: "max_execution_time = {{ php_max_execution_time }}"

- name: "Set PHP max_input_time"
  lineinfile:
     state: present
     dest: '/etc/php.ini'
     regexp: '^(#)?max_input_time = \d'
     line: "max_input_time = {{ php_max_input_time }}"

- name: "Set PHP always_populate_raw_post_data"
  lineinfile: 
     dest: '/etc/php.ini'
     regexp: '^always_populate_raw_post_data ='
     insertafter: '^;always_populate_raw_post_data ='
     line: "always_populate_raw_post_data = {{ php_always_populate_raw_post_data }}"
