---
- name: "Add repo file"
  template: src=mariadb_centos.repo.j2 dest=/etc/yum.repos.d/mariadb.repo owner=root group=root mode=0644

- name: "Install Mariadb"
  yum: name={{ item }} enablerepo=mariadb state=present
  with_items:
    - mariadb-server
    - MySQL-python
    - MariaDB-client

- name: "Start Myql and enabled"
  service: name={{ mysql_service }} state={{ mysql_service_state }} enabled={{ mysql_service_enabled }}



