---
- name: "Installing Percona repository"
  yum:
    pkg: "{{ item }}" 
    state: present
  with_items:
    - "{{ percona_repository }}"

- name: "Install MySQL"
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ percona_packages }}"

- name: "Start Myql and enabled"
  service: 
    name: "{{ mysql_service }}"
    state: "{{ mysql_service_state }}"
    enabled: "{{ mysql_service_enabled }}"

