---
# Install epel
- name: "Install epel-release"
  yum: 
    name: epel-release
    state: latest

- name: "Install dependencies"
  yum: 
    name: "{{ item }}"
    enablerepo: epel
    state: latest
  with_items:
    - fping
    - iksemel
    - net-snmp
    - libxml2-devel
    - libssh2-devel
    - net-snmp-devel
    - curl-devel
    - unixODBC-devel
    - OpenIPMI-devel

