---
# => Install epel
- name: "Install epel-release"
  yum: 
    name: epel-release
    state: latest

- name: "Install dependencies"
  yum: 
    name: "{{ item }}"
    enablerepo: epel
    state: latest
  with_items:
    - "{{ packages }}

